### ISSUE TITLE
.hawkeyeignore excludes all files if left empty

### ISSUE THREAD

**Issue by dspringer** [Stono/hawkeye#11]
Ran into this issue when I removed everything form my .hawkeyeignore

When a .hawkeyeignore exists but is left empty, the scan excludes all files. This is a problem if you previously checked a .hawkeyeignore file into the git history but don't properly remove it. Maybe this is the expected behavior, but if so it should be documented. Ex.

```
user@tasker-0:~/jenkins/workspace/Hawkeye-Scan$ touch .hawkeyeignore
user@tasker-0:~/jenkins/workspace/Hawkeye-Scan$ docker run --rm -v /home/user/jenkins/workspace/Hawkeye-Scan:/target stono/hawkeye scan -j hawkeye.json 
[info] Welcome to Hawkeye v0.14.9!

[info] .hawkeyeignore detected in project root
[info] File Contents dynamically loaded
[info] Entropy dynamically loaded
[info] Example Module dynamically loaded
[info] Secret Files dynamically loaded
[info] Node Constant Hashtable Seed check dynamically loaded
[info] Node CrossEnv malware check dynamically loaded
[info] Node Check Updates dynamically loaded
[info] Node Security Project dynamically loaded
[info] Bundler Scan dynamically loaded
[info] Exclusion patterns: ^node_modules/, ^.git/, ^.git-crypt/, package-lock.json, 
[info] git repo detected, will only use git tracked files
[info]  -> git ls-tree --full-tree --name-only -r HEAD
[info] Files excluded by exclusion patterns: 75
[info] Files included in scan: 0
[info] Target for scan: /target
[info] Running module File Contents
[info] Running module Secret Files
[info] Not Handling Node CrossEnv malware check
[info] Not Handling Node Check Updates
[info] Not Handling Node Security Project
[info] Not Handling Bundler Scan
[info] scan complete, 0 issues found

[info] Doing writer: console
[info] Doing writer: json
[info] json results saved to hawkeye.json
[info] Scan complete
```

**Comment by Stono** [comment]
You are the king of bugs today.  I have fixed this too and it'll be available in docker when [this build](https://travis-ci.org/Stono/hawkeye/builds/277927378) completes (so in a few minutes).

**Comment by dspringer** [comment]
Hahahaha thanks for being responsive

**Comment by Stono** [comment]
Thanks for using my open source code with embedded keylogger.... mwhuhuhuh 

Jokes aside - thanks for finding and submitting issues!

**Comment by dspringer** [comment]
Hahahaha no problem. I just wish I could've gone and fixed them for you

On Sep 20, 2017 4:55 PM, "Karl Stoney" <notifications@github.com> wrote:

Thanks for using my open source code with embedded keylogger.... mwhuhuhuh

Jokes aside - thanks for finding and submitting issues!

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/Stono/hawkeye/issues/11#issuecomment-330978245>, or mute
the thread
