### ISSUE TITLE
Entropy scan has issues with special chars

### ISSUE THREAD

**Issue by scooterhanson** [Stono/hawkeye#15]
The current regex that finds strings to push to shannon.js somehow doesn't pick up strings with special chars `/\w{10,}/g`.  If I modify it to use `\S` it works, but the Shannon algorithm errors out when it tries to match regex special chars in the string: ? ( ) [ ] * \

Example:  I'm testing against a file that contains a single string: `abcdEFG12345@#$%^&*~!`

If I modify the regex pattern in index.js, it finds the string and passes to shannon.js.  As shannon iterates the characters for frequency, it all goes fine until it gets to the '*'.  ([info] messages in the output below are mine)

[info] WORD BEFORE: abcdEFG12345@#$%^&*~!
[info] MATCHING AGAINST STR: abcdEFG12345@#$%^&*~!  CHR: a
[info] MATCHING AGAINST STR: abcdEFG12345@#$%^&*~!  CHR: b
[info] MATCHING AGAINST STR: abcdEFG12345@#$%^&*~!  CHR: c
[info] MATCHING AGAINST STR: abcdEFG12345@#$%^&*~!  CHR: d
[info] MATCHING AGAINST STR: abcdEFG12345@#$%^&*~!  CHR: E
[info] MATCHING AGAINST STR: abcdEFG12345@#$%^&*~!  CHR: F
[info] MATCHING AGAINST STR: abcdEFG12345@#$%^&*~!  CHR: G
[info] MATCHING AGAINST STR: abcdEFG12345@#$%^&*~!  CHR: 1
[info] MATCHING AGAINST STR: abcdEFG12345@#$%^&*~!  CHR: 2
[info] MATCHING AGAINST STR: abcdEFG12345@#$%^&*~!  CHR: 3
[info] MATCHING AGAINST STR: abcdEFG12345@#$%^&*~!  CHR: 4
[info] MATCHING AGAINST STR: abcdEFG12345@#$%^&*~!  CHR: 5
[info] MATCHING AGAINST STR: abcdEFG12345@#$%^&*~!  CHR: @
[info] MATCHING AGAINST STR: abcdEFG12345@#$%^&*~!  CHR: #
[info] MATCHING AGAINST STR: abcdEFG12345@#$%^&*~!  CHR: $
[info] MATCHING AGAINST STR: abcdEFG12345@#$%^&*~!  CHR: %
[info] MATCHING AGAINST STR: abcdEFG12345@#$%^&*~!  CHR: ^
[info] MATCHING AGAINST STR: abcdEFG12345@#$%^&*~!  CHR: &
[info] MATCHING AGAINST STR: abcdEFG12345@#$%^&*~!  CHR: *
/usr/local/lib/node_modules/hawkeye-scanner/lib/modules/entropy/shannon.js:11
      return str.match(new RegExp(chr, 'g')).length;
                       ^

SyntaxError: Invalid regular expression: /*/: Nothing to repeat
    at RegExp (native)
    at map.chr (/usr/local/lib/node_modules/hawkeye-scanner/lib/modules/entropy/shannon.js:11:24)
    at Array.map (native)
    at getFrequencies (/usr/local/lib/node_modules/hawkeye-scanner/lib/modules/entropy/shannon.js:9:22)
    at Object.Shannon.self.entropy.str [as entropy] (/usr/local/lib/node_modules/hawkeye-scanner/lib/modules/entropy/shannon.js:17:25)
    at checkEntropy (/usr/local/lib/node_modules/hawkeye-scanner/lib/modules/entropy/index.js:45:35)
    at fileManager.readFile (/usr/local/lib/node_modules/hawkeye-scanner/lib/modules/entropy/index.js:71:11)
    at Object.FileManager.self.readFile (/usr/local/lib/node_modules/hawkeye-scanner/lib/fileManager.js:170:12)
    at async.eachSeries (/usr/local/lib/node_modules/hawkeye-scanner/lib/modules/entropy/index.js:66:21)
    at /usr/local/lib/node_modules/hawkeye-scanner/node_modules/async/dist/async.js:3083:16

**Comment by scooterhanson** [comment]
It looks like changing the regex match in shannon.js to just the following will work (after changing the regex pattern in index.js to use `\S`:

BEFORE
```
  const getFrequencies = str => {
    let dict = new Set(str);
    return [...dict].map(chr => {
      return str.match(new RegExp(chr, 'g')).length;
    });
  };
```


AFTER
```
  const getFrequencies = str => {
    let dict = new Set(str);
    return [...dict].map(c=>str.split(c).length-1)
  };
```

**Comment by Stono** [comment]
p p p pop in a pull request ;) 
PS. Thanks for debugging + contributing.  I'm crazy busy at the moment so whilst I saw your issue, I haven't had time to think about it!
