### ISSUE TITLE
RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by jagregory** [Stono/hawkeye#16]
Using a nodejs project on the hosted Hawkeye, it goes bang pretty quickly on one particular repo. Only seems to occur on this one repo though, not any others with the same stack.

```
Hawkeye starting...

Cloning [ redacted ]
[info] Welcome to Hawkeye v0.14.12!

[info] File Contents dynamically loaded
[info] Entropy dynamically loaded
[info] Example Module dynamically loaded
[info] Secret Files dynamically loaded
[info] Node Constant Hashtable Seed check dynamically loaded
[info] Node CrossEnv malware check dynamically loaded
[info] Node Check Updates dynamically loaded
[info] Node Security Project dynamically loaded
[info] Bundler Scan dynamically loaded
[info] Exclusion patterns: ^node_modules/, ^.git/, ^.git-crypt/, package-lock.json
[info] git repo detected, will only use git tracked files
[info] Files excluded by exclusion patterns: 0
[info] Files included in scan: 663
[info] Running module File Contents
[warn] File which exceeds 80kb limited detected: /tmp/repo-RtDjGM/test/crm-stub/fixtures/api/data/v8.1/GlobalOptionSetDefinitions.json
[warn] File which exceeds 80kb limited detected: /tmp/repo-RtDjGM/yarn.lock
/hawkeye/lib/modules/content/index.js:19
    return item => {
           ^

RangeError: Maximum call stack size exceeded
    at Object.item [as contentMatcher] (/hawkeye/lib/modules/content/index.js:19:12)
    at Object.pattern.check (/hawkeye/lib/modules/content/index.js:45:34)
    at fileManager.readFile (/hawkeye/lib/modules/content/index.js:67:21)
    at Object.FileManager.self.readFile (/hawkeye/lib/fileManager.js:170:12)
    at async.eachSeries (/hawkeye/lib/modules/content/index.js:65:23)
    at /hawkeye/node_modules/async/dist/async.js:3083:16
    at replenish (/hawkeye/node_modules/async/dist/async.js:946:17)
    at iterateeCallback (/hawkeye/node_modules/async/dist/async.js:931:17)
    at /hawkeye/node_modules/async/dist/async.js:906:16
    at fileManager.readFile (/hawkeye/lib/modules/content/index.js:68:13)
Request complete with errors.
```

**Comment by scooterhanson** [comment]
This is a strange one.  I haven't dug into it yet but in a project with many src trees, it appears that there is a certain threshold in directory depth from where I can run the scan successfully.  I'm not saying this is it, but when I cd deeper I can scan the CWD successfully.  No rhyme or reason to the depth yet, but I'll keep digging.

**Comment by scooterhanson** [comment]
115 files max?

**Comment by Stono** [comment]
@scooterhanson Please see: https://github.com/Stono/hawkeye/commit/39a8468c92ef2915a8800971c21e0725c0dcfd84 and let me know your thoughts!

**Comment by jagregory** [comment]
This looks great. Do you know when it'll make it into the hosted deployment? I'm still seeing the issue over there right now.

**Comment by Stono** [comment]
@jagregory sorry mate, I'll be within the next day or so.  I found a few issues on the hosted version that I'm just working through but start a new job tomorrow so it's all been a little hectic!

**Comment by Stono** [comment]
@jagregory just pushed 0.15.0 to the SaaS version; unfortunately the recent changed I have made resulted in me having to reset the history and notification database, so you'll need to reset that up.  The joys of beta software ;)

Lemme know if it works OK for you.
