### ISSUE TITLE
File size limit option

### ISSUE THREAD

**Issue by scooterhanson** [Stono/hawkeye#26]
Can we make the file size limit configurable at runtime or in the rc file?

**Comment by Stono** [comment]
I've been thinking about this one more especially now we've added the ability to scan jar files.  I think it needs to be configurable/overridable per module

**Comment by thenathanjones** [comment]
Have you had more of a thought about how you may want this done? I might take some time to have a look at how I can help. I want to use this in a setup with Spring Boot and because it creates fat jar files, the size limit now makes it basically unusable for my application.

**Comment by felixhammerl** [comment]
Obsolete, see https://github.com/Stono/hawkeye/issues/27
