### ISSUE TITLE
Scan only git-staged files

### ISSUE THREAD

**Issue by scooterhanson** [Stono/hawkeye#28]
I am using hawkeye in a pre-commit hook and I'd love to be able to only run the scan against changed files.

**Comment by Stono** [comment]
I'd be interested in a pull request in the README for how you implemented this to help others :-)

**Comment by scooterhanson** [comment]
You bet.  Plus, I've already got this git-staged feature working, just need to get the time to do a PR.

**Comment by Stono** [comment]
https://github.com/Stono/hawkeye/pull/17
