### ISSUE TITLE
False positives

### ISSUE THREAD

**Issue by Rajik** [Stono/hawkeye#39]
There are a few gems that require arguments like aws_access_key_id to be set while instantiation -  we just pass in the arguments and not set the value explicitly. Example,

`Fog::Storage.new({
                             :provider => 'AWS',
                             :aws_access_key_id => access_key_id,
                             :aws_secret_access_key => secret_access_key,
                         })`

After your recent release, this is being reported as a critical vulnerability. Instead of scanning the code for strings like 'aws_access_key_id' and 'aws_access_key_id', wont the entropy scanner catch if the value is being explicitly set? Thoughts??

**Comment by Stono** [comment]
@Rajik I agree that these shouldn't be down as critical because pattern matching is flakey at best.  My gut is to actually lower all the pattern based matches in https://github.com/Stono/hawkeye/blob/master/lib/modules/content/data.js to low - what do you think?

**Comment by Rajik** [comment]
Yes that makes sense too. Except for the one that checks for private key.

**Comment by Stono** [comment]
Fancy submitting a pull request with your proposed changes? :)

**Comment by Rajik** [comment]
Sure, will do it right away :-)
