### ISSUE TITLE
Upgrading to a Release Candidate version

### ISSUE THREAD

**Issue by mohamednajiullah** [Stono/hawkeye#45]
Hi

We're using hawkeye to scan our api code. We use the mongodb driver in our api and we noticed that there is a suggestion to upgrade to a release candidate version of the driver

high  |   Module is one or more major  versions out of date | mongodb | Update to 3.0.0-rc0 
         
The above message appears even when we upgraded our driver to the latest stable version. I feel hawkeye should include suggestions for upgrading to stable versions and not release candidate versions.

**Comment by Stono** [comment]
@mohamednajiullah this is a good point however as all hawkeye is doing is wrapping the underlying [npm check updates](https://github.com/tjunnone/npm-check-updates) modules, there isn't a lot I can do about it here so I would suggest raising your issue over in that repo.

From their documentation it appears that it should only be suggested stable versions, and that can be overrided, but hawkeye doesn't use this flag:

```
   -n, --newest                 find the newest versions available instead of the latest stable versions
```
