### ISSUE TITLE
Node Security Project shutting down

### ISSUE THREAD

**Issue by Stono** [Stono/hawkeye#66]
nsp is used for nodejs dep checks.

https://blog.npmjs.org/post/175511531085/the-node-security-platform-service-is-shutting

**Comment by felixhammerl** [comment]
It look like they are still keeping nsp around until `npm audit` has reached feature parity, but apparently `npm audit` does a better job at scanning than nsp these days.

**Comment by felixhammerl** [comment]
I plan replacing `nsp` with `npm audit --json`, comparable to how we've handled the `npm outdated`.

I am not set on whether to include or exclude dev dependencies. I feel they should be included, as many folks have things like webpack and babel in their dev dependencies, whose transpiled sources could reasonably include vulnerabilities...

**Comment by Stono** [comment]
I think this is an interesting point and I agree, take the recent BA hack was was linked to outdated UI components (modernizer).
