### ISSUE TITLE
TravisCI is trying to deploy pull requests

### ISSUE THREAD

**Issue by ineffyble** [Stono/hawkeye#79]
### Description

The build for my pull request at https://travis-ci.org/Stono/hawkeye/builds/435602710 appears to be running the Docker deploy.sh - this is because the TRAVIS_BRANCH is master (it's the master branch on my forked repo).

### Steps to Reproduce

1. Fork the hawkeye repo to another user's GitHub.
2. Make a commit on the fork's master branch.
3. Create a pull request to Stono/hawkeye/master from your fork.

**Expected behavior:** Deploy step does not run.

**Actual behavior:** Deploy step runs, fails at Docker push with incorrect username/password.

**Comment by Stono** [comment]
Thanks @ineffyble - fixed in https://github.com/Stono/hawkeye/commit/9735f84a7df637eb7712967d9bea52815b060038

**Comment by felixhammerl** [comment]
Just reopening the issue. I feel that the deploy should only run on tags. Thoughts?
