### ISSUE TITLE
I want to maintain hawkeye

### ISSUE THREAD

**Issue by dgonzalez** [Stono/hawkeye#80]
Hey,

As you mention in the `README.md` I'd be more than happy to help maintaining hawkeye. I can give you more context on my background but here is one example of my work: https://github.com/nearform/gammaray

Thanks

**Comment by pxlpnk** [comment]
I am happy to support @dgonzalez and move hawkeye forward.

**Comment by felixhammerl** [comment]
Excellent to hear that you're interested! There's generally always a bunch of things where we welcome help. For example, we encourage people to send pull requests on issues where we welcome contribution, open issues on things where we lack support or where we could improve, help in bug triage, help reviewing pull requests, etc.. 

In terms of achieving world domination with Hawkeye, one things that's highly appreciated is bringing tools to our collective attention that we would benefit from supporting, and possibly trying your hand in adding a module for it.

It always depends on how much time you have at your disposal for helping out.

**Comment by dgonzalez** [comment]
Super!

We have few things in mind. Let me PR some of them if I can find time.

**Comment by felixhammerl** [comment]
Please note that you can also open a PR for work in progress, just to get feedback. We'll add the `pr-work-in-progress` label to it, but you can benefit from getting feedback on the PR.
In the meantime, feel free to also join us on our [Gitter channel](https://gitter.im/hawkeye-scanner/Lobby) for a chat and feedback on your ideas.

If that's ok for you, I would close this issue for now.
